### ISSUE TITLE
1.18 update

### ISSUE THREAD

**Issue by Aurelien30000** [KyoriPowered/adventure-platform-fabric#13]
Due to the changes in 1.18 update, adventure-platform-fabric needs adaptations and fixes, here is a crash I faced with:

https://paste.domicraft.fr/afovutodow.yaml

Thanks!

**Comment by kezz** [comment]
It was mentioned in the Discord but I'll just reiterate here, `adventure-platform` is not of super high priority for the team anymore. If anyone would like to submit a PR that updates the project to support 1.18, such a PR would be very welcome :)

**Comment by zml2008** [comment]
the changes are pretty minimal - I have a local branch to do the update

**Comment by zml2008** [comment]
5.0.0-SNAPSHOT
