### ISSUE TITLE
1.19 Registry sync issue on login when not present on client

### ISSUE THREAD

**Issue by jpenilla** [KyoriPowered/adventure-platform-fabric#39]
This is probably a fabric api issue but I am creating this for tracking purposes

![Zdc9QuJ](https://user-images.githubusercontent.com/11360596/173246144-f86bc3ca-5bdd-4cd6-8556-0b292984003b.png)

**Comment by zml2008** [comment]
yeah, solution for now is probably just lazy registering the command arguments with the registry only if they're used in a command

long term, I'm planning to move the platform to build against quilt, where colonel has become a fully supported part of the QSL commands api
