### ISSUE TITLE
calls to ConnectionAccess.getChannel should check for null as the channel field can be null

### ISSUE THREAD

**Issue by MehVahdJukaar** [KyoriPowered/adventure-platform-fabric#87]
Causes this issues in some circumstances
`Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null`

**Comment by zml2008** [comment]
no stacktrace? no version of the mod?

**Comment by MehVahdJukaar** [comment]
That's not an issue I found myself. You can find a log in the issue I linked

**Comment by zml2008** [comment]
That issue is for 1.19.2, which is no longer supported.

**Comment by MehVahdJukaar** [comment]
Hehe, I'm not supporting 1.19.2 either

**Comment by zml2008** [comment]
Ok, looking back at this now that another few users have asked about it (I've been told most big modpacks are still on 1.19.2), and looking at the behaviour of Fabric API's fake player API, I've backported the null check for player channels as [v5.5.2](https://github.com/KyoriPowered/adventure-platform-fabric/releases/tag/v5.5.2) -- there's a jar attached to the release that should function as a drop-in fix for users.
